# Generated by Django 5.2.9 on 2026-01-02 22:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopindexpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in dollars', max_digits=10)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - leave blank to auto-generate', max_length=100, unique=True)),
                ('description', wagtail.fields.RichTextField(help_text='Product description and details')),
                ('in_stock', models.BooleanField(default=True, help_text='Whether the product is currently available')),
                ('featured', models.BooleanField(default=False, help_text='Show this product in featured sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ForeignKey(blank=True, help_text='Main product image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.productpage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
